insert into Ateneo (nome, URL, tipologia, citta, regione, introduzione, costo_medio, num_borsaStudio, posizioneGraduatoria) values
('Università degli studi di Bologna', 'www.unibo.it', 'pubblica', 'Bologna', 'Emilia Romagna', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('Università degli studi di Padova', 'www.unipd.it', 'pubblica', 'Padova', 'Veneto', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('Università degli Studi del Molise', 'www.unimol.it', 'pubblica', 'Campobasso', 'Molise', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('Sigmund Freud University', 'www.milano-sfu.it', 'privata', 'Milano', 'Lombardia', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria'),
('nome', 'URL', 'tipologia', 'citta', 'regione', 'introduzione', 'costo_medio', 'nume_borsaStudio', 'posizioneGraduatoria');

insert into ClassediLaurea (num_classe, denominazione, illustrazione, area_disciplinare, gruppo_disciplinare, durata_stimata) values
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata'),
('num_classe', 'denominazione', 'illustrazione', 'area_disciplinare', 'gruppo_disciplinare', 'durata_stimata');

insert into CorsodiStudio (ateneo, classe_laurea, nome, accesso, URL) values
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL'),
('ateneo', 'classe_laurea', 'nome', 'accesso', 'URL');


insert into Utente (email, password, nome, cognome, data_nascita, genere) values
('viscontisante@fastwebnet.it','rWbOWXhe','Ida','Gremese','1977-05-13','ND'),
('costalongalivio@hotmail.it','RGhoDtQc','Rocco','Botticelli','1971-09-10','M'),
('fiorinocatenazzi@yahoo.com','yIdxakZN','Alderano','Vecellio','1989-07-19','ND'),
('lodovicovismara@live.com','UIYnlCto','Adelasia','Sforza','1973-12-13','F'),
('redipietro@virgilio.it','YpVjTkac','Morena','Druso','1996-12-17','F'),
('talianigaspare@alice.it','ZcmpPtjt','Toni','Greco','1986-07-21','F'),
('doloresbarozzi@libero.it','yYodQMru','Antonello','Bersani','2014-12-05','F'),
('dantebarillaro@live.com','hLXhcZji','Calcedonio','Zola','2002-04-18','M'),
('mario98@live.com','sIdIXYlw','Jacopo','Rubbia','1987-07-14','ND'),
('visintinisaverio@alice.it','vAMNXPQq','Iolanda','Piane','2005-05-14','M'),
('dmannoia@outlook.com','HnGgDSFi','Leone','Sansoni','1984-10-18','M'),
('teresamontanari@virgilio.it','LcVhLPYn','Allegra','Orlando','2003-01-15','ND'),
('eugenia83@libero.it','ylLJySAv','Stefani','Maggioli','1992-02-21','M'),
('dgravina@live.com','sgwFgljp','Pomponio','Badoglio','2017-05-01','ND'),
('gaspare67@live.com','pbpGjIWU','Filippo','Gussoni','1972-07-01','F'),
('lamberto08@libero.it','YHZjTPDu','Nino','Piazzi','1981-03-02','F'),
('paulina14@vodafone.it','STJWqAkx','Carolina','Ferrucci','2004-02-11','M'),
('mazzacuratilazzaro@hotmail.it','zKMuXSiR','Marco','Panzera','2021-12-13','ND'),
('beatricebenussi@tiscali.it','GhKSkNVi','Arnulfo','Sermonti','1977-09-30','ND'),
('kgiradello@alice.it','UIWnmloe','Piergiorgio','Trobbiani','1975-06-06','M'),
('romolosatriani@hotmail.it','vDpeychl','Tina','Bocca','1994-06-19','ND'),
('sabatino33@virgilio.it','SQEfqSnj','Morena','Satta','2015-12-21','M'),
('riccatileopoldo@fastwebnet.it','dFpWtwdL','Camillo','Pepe','1976-02-06','ND'),
('bmarzorati@fastwebnet.it','VfnwWYPU','Adelasia','Gigli','1985-05-17','M'),
('bergogliotemistocle@outlook.com','isHDwJfJ','Rodolfo','Scarpetta','1972-09-11','F'),
('oletta@outlook.com','xXBGedgu','Licia','Pennetta','1976-08-17','F'),
('gvalguarnera@hotmail.it','qXSzCSlx','Luciano','Proietti','2018-01-07','F'),
('piermaria89@live.com','rBeIlEVt','Galasso','Amaldi','1987-09-15','F'),
('rosa42@tim.it','XWisoERt','Ilaria','Juvara','1994-05-11','ND'),
('saveriomonteverdi@hotmail.it','ZqZVpeGz','Oreste','Brancaccio','2003-01-19','ND'),
('pergolesisaverio@live.com','BbVNHnXA','Michelangelo','Scaramucci','2003-05-13','M'),
('geronimo66@libero.it','HwGQDRcL','Claudio','Scandone','1995-04-28','M'),
('chiara36@tim.it','ZPwkDpzi','Michela','Trevisani','1975-05-02','M'),
('tresoldigriselda@gmail.com','tHwZLNaP','Lodovico','Gentilini','1983-08-23','M'),
('acasarin@live.com','zJImGGjl','Liberto','Bruscantini','1979-04-20','M'),
('estaglieno@libero.it','rHzpLGdm','Margherita','Smirnoff','2014-09-23','ND'),
('lorenzo07@poste.it','IAeMvtbB','Gastone','Borroni','1978-12-03','M'),
('ozampa@libero.it','HmvvZiJz','Atenulf','Carullo','2000-05-12','ND'),
('giustinoargan@live.com','JcxWCmHJ','Flavio','Galiazzo','1981-06-04','ND'),
('marcella17@yahoo.com','WaGrmNvA','Salvatore','Argento','2005-12-03','ND'),
('jbelletini@libero.it','YiDDqRDt','Maria','Mondadori','2009-10-14','M'),
('adinolfifredo@gmail.com','doIHVith','Amanda','Rosselli','1981-12-10','M'),
('ymolesini@tin.it','dKlACfPI','Ranieri','Innocenti','2006-10-23','ND'),
('fanuccitina@vodafone.it','QQnYBcTY','Ugolino','Viviani','1996-09-22','ND'),
('omortati@tiscali.it','wbWCFroC','Alina','Cabibbo','1982-10-01','ND'),
('ninoamato@tiscali.it','eBklbCFD','Gionata','Tutino','2012-09-18','M'),
('guarino67@poste.it','dxwdAunl','Carla','Comeriato','1982-06-26','F'),
('vincenzo37@gmail.com','rZGehlgu','Olga','Caetani','1983-05-04','M'),
('xcarocci@gmail.com','RUktSczg','Barbara','Tozzi','2010-08-06','M'),
('ssalieri@hotmail.com','hFXfHTDp','Lamberto','Manzoni','1982-10-09','M'),
('donatellaleonetti@virgilio.it','mkvbqzIj','Maria','Donini','1971-04-04','F'),
('azegliorossellini@alice.it','ZFcIEDmV','Coriolano','Civaschi','1990-09-19','F'),
('maria06@live.com','IXCPNsni','Ninetta','Sordi','1981-01-28','ND'),
('evangelistasurian@tele2.it','ourkZyWl','Melina','Cappelli','1972-01-26','F'),
('rolandosismondi@gmail.com','dXPZATef','Alfio','Aporti','2003-02-20','M'),
('asmundogianmarco@yahoo.com','ihnKAwPK','Alberto','Ferrucci','2006-06-20','M'),
('jspallanzani@gmail.com','fzIhRjDT','Enzio','Jacuzzi','1998-04-05','M'),
('melissa66@tele2.it','ehDBdoQI','Alberto','Saragat','2003-05-24','F'),
('taccolaangelo@outlook.com','PnCebdtC','Gabriella','Govoni','1984-04-09','M'),
('gianfranco54@vodafone.it','jWPUDkCM','Rosalia','Leblanc','1994-04-09','ND'),
('venancio12@poste.it','yCLYQObj','Michelotto','Brunelleschi','1970-12-04','M'),
('nicolomatteotti@gmail.com','bnxsaXaU','Anita','Coardi','2022-06-10','F'),
('tizianagarozzo@live.com','bccZKbmB','Salvatore','Oscuro','2016-12-22','F'),
('paltrinierisilvia@live.com','XIoUsrwH','Laura','Odescalchi','1973-07-19','F'),
('adrianamimun@gmail.com','cZXuiQTY','Lazzaro','Cuzzocrea','1992-02-04','ND'),
('reggefiorino@vodafone.it','CtLgxpDW','Sandra','Tedesco','2012-01-29','M'),
('ernesto08@fastwebnet.it','wTLDRIna','Piergiuseppe','Cimarosa','2020-10-05','F'),
('hcallegaro@fastwebnet.it','HDjLaWCi','Torquato','Petruzzi','2007-03-30','M'),
('fscarpetta@gmail.com','aSmaMdwN','Oreste','Caironi','1992-05-13','F'),
('temanuelli@vodafone.it','nRghCqxl','Gelsomina','Baracca','2011-08-28','F'),
('nanni24@virgilio.it','GxNWlmoc','Giovanni','Rusticucci','2014-10-14','F'),
('lucia43@vodafone.it','QtleGxLr','Rosalia','Ariasso','2015-05-17','M'),
('berlusconimassimo@gmail.com','nqCMLnTu','Antonello','Galtarossa','1970-08-21','M'),
('milanesiagnolo@live.com','BruETVUQ','Rodolfo','Sermonti','1994-10-03','M'),
('vendittigionata@gmail.com','zrBKYnOh','Laureano','Barsanti','1997-06-24','M'),
('livio13@gmail.com','vbTibSzu','Tina','Rubbia','1979-12-28','F'),
('bassocaterina@fastwebnet.it','RqncySmO','Valeria','Donà','2006-12-28','F'),
('bbocelli@tiscali.it','haHyLbHp','Benvenuto','Staglieno','2003-12-16','M'),
('gabbanamatilda@tin.it','WhwipfxH','Allegra','Ubaldi','1971-04-20','F'),
('luigibalbo@gmail.com','qKJzubcL','Calcedonio','Costalonga','1986-01-29','M'),
('rpavanello@tin.it','MYLtEZnM','Zaira','Filangieri','1970-08-21','F'),
('giacinto14@libero.it','ZxRATuwK','Marcantonio','Collodi','2016-02-07','ND'),
('barsantimichelotto@hotmail.it','JkkxjhJf','Fabia','Zamengo','2020-03-14','ND'),
('rosamalenchini@live.com','YohcleiM','Fausto','Mercalli','1973-09-21','M'),
('mauro28@poste.it','XnPGdrsr','Vittoria','Bruno','1990-01-02','M'),
('niscoromniadelasia@gmail.com','sVkrRDQb','Pier','Vitturi','2016-11-08','F'),
('pacomiomarissa@alice.it','lUReVVHV','Angelo','Crisafulli','1996-06-03','ND'),
('farandaiolanda@libero.it','iwwaFPbs','Lolita','Salieri','1991-10-27','ND'),
('mirco68@vodafone.it','wXYmnsVE','Gianfrancesco','Giacometti','1991-02-16','M'),
('ornella36@tim.it','unGSnOiD','Fabia','Maggioli','1993-04-17','M'),
('tizianamontalti@gmail.com','ekbxpEVw','Anita','Albertini','2011-05-13','ND'),
('giulioflaiano@poste.it','jurkrvfn','Silvio','Marangoni','2014-12-27','M'),
('gpalmisano@libero.it','GektzkPn','Luciana','Luzi','2019-10-17','ND'),
('bruno33@hotmail.com','IuJoMlHV','Silvia','Papafava','1972-05-17','M'),
('izoppetto@yahoo.com','RJITGjNx','Antonia','Casadei','2014-01-30','M'),
('dallanicola@fastwebnet.it','OkfXyqGD','Paloma','Pometta','1982-09-14','ND'),
('gianlucacianciolo@gmail.com','IlOgtgsz','Guarino','Gullotta','1983-07-15','F'),
('gemmamorucci@virgilio.it','WgpfvbmB','Flavia','Coardi','1999-07-18','M'),
('mlittizzetto@hotmail.com','QxjhnBhG','Pierina','Roncalli','2001-03-03','F'),
('fabriziapisano@libero.it','PLrkgdKf','Rembrandt','Trincavelli','2001-08-18','ND');


insert into Valutazione (nome_utente, classe_laurea, data, commento, p_complessivo, p_acc_fisica, p_servizio_inclusione, tempestivita_burocratica, p_insegnamento) values
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento'),
('nome_utente', 'classe_laurea', 'data', 'commento', 'p_complessivo', 'p_acc_fisica', 'p_servizio_inclusione', 'tempestivita_burocratica', 'p_insegnamento');
